version: "1"
services:
  golang:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
    image: ddd-sample-golang
    container_name: ddd-sample-golang
    volumes:
      - ../golang:/app
    ports:
      - "3000:3000"
    tty: true

  gcloud:
    build:
      context: ../
      dockerfile: ./docker/gcloud/Dockerfile
    image: ddd-sample-gcloud
    container_name: ddd-sample-gcloud
    volumes:
      - ../:/app
    tty: true
