version: "2.0"
services:
  golang:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
    image: ddd-sample-golang
    container_name: ddd-sample-golang
    volumes:
      - ../golang:/go/src
      - ./datastore:/tmp/datastore
    # command: /bin/bash -c "source ~/.bashrc && dev_appserver.py --host 0.0.0.0 --datastore_path=/tmp/datastore/data --admin_host 0.0.0.0 app.yaml"
    ports:
      - 8080:8080
      - 8000:8000
    tty: true
    stdin_open: true
