version: "1"
services:
  golang:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
    image: ddd-sample-golang
    container_name: ddd-sample-golang
    volumes:
      - ../golang:/app
    ports:
      - "3000:3000"
    links:
      - datastore:datastore
    environment:
      - "DATASTORE_EMULATOR_HOST=datastore:8059"
      - "DATASTORE_PROJECT_ID=test-golang-kamite"
    depends_on:
      - datastore
    tty: true

  datastore:
    image: google/cloud-sdk
    container_name: ddd-sample-datastore
    environment:
      - PROJECT_ID=test-golang-kamite
    command: /bin/bash -c "gcloud beta emulators datastore start --host-port 0.0.0.0:8059 --project $$PROJECT_ID --data-dir /data"
    volumes:
      - ./datastore:/data

  gcloud:
    build:
      context: ../
      dockerfile: ./docker/gcloud/Dockerfile
    image: ddd-sample-gcloud
    container_name: ddd-sample-gcloud
    volumes:
      - ../:/app
    tty: true
