version: "1"
services:
  golang:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
    image: ddd-sample-golang
    container_name: ddd-sample-golang
    volumes:
      - ../golang:/app
    command: /bin/bash -c "source ~/.bashrc && dev_appserver.py --host 0.0.0.0 --admin_host 0.0.0.0 app.yaml"
    ports:
      - 8080:8080
      - 8000:8000
    tty: true
    stdin_open: true
