FROM gcr.io/google.com/cloudsdktool/cloud-sdk:latest

COPY ./gcloud/app /app
WORKDIR /app

# RUN curl https://sdk.cloud.google.com | bash && /root/google-cloud-sdk/install.sh
# RUN source /root/.bashrc
# RUN /root/google-cloud-sdk/bin/gcloud init
