version: "1"
services:
  golang:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
    image: ddd-sample-golang
    container_name: ddd-sample-golang
    volumes:
      - ../backend:/app
    ports:
      - "3000:3000"
    tty: true
